#!/bin/bash

echo "🎉 Client Onboarding Service - ГОТОВИЙ"
echo "==============================================="
echo ""
echo "🌐 URL: https://manage.telegramd.com/"
echo "📄 Сторінки:"
echo "   - https://manage.telegramd.com/           (головна)"
echo "   - https://manage.telegramd.com/clients.html (управління клієнтами)"
echo ""
echo "🔐 Авторизація:"
echo "   Username: admin"
echo "   Password: ***"
echo ""
echo "📊 Статус:"
echo "   Backend:  $(sudo systemctl is-active client-onboarding-backend)"
echo "   Frontend: $(sudo systemctl is-active client-onboarding-frontend)"
echo "   Nginx:    $(sudo systemctl is-active nginx)"
echo ""
echo "🔒 SSL: активний до 2026-01-12"
echo ""
echo "💡 Порада: Очистіть кеш браузера (Ctrl+Shift+R)"
echo ""
