#!/bin/bash

echo "📊 Client Onboarding Service - Детальний статус"
echo "================================================"
echo ""
echo "🔧 Systemd сервіси:"
echo "  Backend:  $(sudo systemctl is-active client-onboarding-backend)"
echo "  Frontend: $(sudo systemctl is-active client-onboarding-frontend)"
echo "  Nginx:    $(sudo systemctl is-active nginx)"
echo ""
echo "🔐 Авторизація:"
echo "  Username: admin"
echo "  Файл паролів: /etc/nginx/.htpasswd"
echo ""
echo "🌐 Доступ:"
echo "  URL: http://18.220.173.169/"
echo "  При першому відкритті буде запит логіну та паролю"
echo ""
echo "🔄 Команди управління:"
echo "  sudo systemctl restart client-onboarding-backend"
echo "  sudo systemctl restart client-onboarding-frontend"
echo "  sudo systemctl restart nginx"
echo "  sudo journalctl -u client-onboarding-backend -f"
echo ""
